### ISSUE TITLE
Latest release is not on crates.io

### ISSUE THREAD

**Issue by rparrett** [Corrosive-Games/bevy-parallax#14]
`0.1.3` was released here 4 days ago, but the [latest version on crates.io](https://crates.io/crates/bevy-parallax/versions) is still `0.1.2`.

**Comment by zicklag** [comment]
Also relevant: #13.

We may not want to publish 0.1.3 and instead publish as `0.2.0`.

**Comment by cdsupina** [comment]
Just published, closing this. Sorry for the delay!
