### ISSUE TITLE
Repeat direction should be set separately from speed

### ISSUE THREAD

**Issue by FishHawk** [Corrosive-Games/bevy-parallax#26]
I want the background to repeat only in the x-direction, and scroll in the xy-direction. But if I set `LayerSpeed::Bidirectional`, the image also repeats in the y-direction.

Like this:
<img width="1005" alt="image" src="https://github.com/Corrosive-Games/bevy-parallax/assets/46566858/e3bda8b1-7346-43bb-8c42-323779ae6ab4">

**Comment by FishHawk** [comment]
Plus Y-axis parallax scrolling. When moving up and down, different layers should have different y offset.

Like this:

https://github.com/Corrosive-Games/bevy-parallax/assets/46566858/e297ec11-8dfc-4e1e-bf0f-d81065b413ed

By the way, I have already reimplemented the parallax scrolling system.

**Comment by ettoreleandrotognoli** [comment]
Hello @FishHawk 
I updated the cyberpunk example with the new feature, hope that it is what you expect:
https://github.com/Corrosive-Games/bevy-parallax/assets/4960560/4d656505-41bd-48ae-93ff-3cf64fd4a3f6

**Comment by FishHawk** [comment]
That's exactly what I wanted. Thanks.
