### ISSUE TITLE
Re-creating parallax causes panic

### ISSUE THREAD

**Issue by odecay** [Corrosive-Games/bevy-parallax#27]
I get this panic on re-loading a game from the main menu
```
thread 'Compute Task Pool (1)' panicked at 'Attempting to create an EntityCommands for entity 18v0, which doesn't exist.', /home/user/.cargo/git/checkouts/bevy-parallax-5ee5078bec517e3b/c3a36cc/src/lib.rs:43:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_parallax::create_parallax_system`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
I believe it is due to 

https://github.com/Corrosive-Games/bevy-parallax/blame/c3a36cc7a1eafd8263c3c70a15c776e71580ea9a/src/lib.rs#L42-L58

This system appears to despawn the entities contained in `ParallaxCameraComponent` and then tries to add components to them after the fact which could result in creating an `EntityCommands` for an entity which doesn't exist.

**Comment by ettoreleandrotognoli** [comment]
Hello, I'm not sure if I get what you think the issue is

```rs

  // here we despawn the entities
  for entity in parallax.entities.iter() {
      commands.entity(*entity).despawn_recursive(); // the line 43 is this one
  }
  
  if let Some(viewport) = &camera.viewport {
      window_size = viewport.physical_size.as_vec2();
  }
  
  // here we create new entities and replace the old ones
  parallax.entities = event.create_layers(
      &mut commands,
      window_size,
      &asset_server,
      &mut texture_atlases,
      parallax.render_layer,
  );
  
  // here we set the RenderLayer for each one of the new entities
  for entity in parallax.entities.iter() {
      commands
          .entity(*entity) // I don't think the error is here, as we just created the entities
          .insert(RenderLayers::from_layers(&[parallax.render_layer]));
  }
```

I guess that we'are trying to despawn, on the line 43, something that was already removed
Do you agree? And I don't know how it was removed before, in the parallax library this is the only call to despawn/remove that I found

**Comment by ettoreleandrotognoli** [comment]
I created a reload example, just to be sure that is working for simple cases

https://github.com/ettoreleandrotognoli/bevy-parallax/blob/issue-27/examples/reload.rs

**Comment by odecay** [comment]
> I guess that we'are trying to despawn, on the line 43, something that was already removed Do you agree? And I don't know how it was removed before, in the parallax library this is the only call to despawn/remove that I found

I see what you mean, I missed the chunk where a new set of parallax entities are set. I've probably missed something elsewhere, I'll have to look through my code and see if I can provide more details. For more context its not for hot reload, Its when I exit to the main menu and reload from the beginning of a level. When exiting the game we despawn every entity but the camera and the window.

**Comment by ettoreleandrotognoli** [comment]
Got it, I think I was able to reproduce the error

I added this:
```rs
pub fn despawn_all(
    mut commands: Commands,
    keyboard_input: Res<Input<KeyCode>>,
    all_query: Query<Entity, (Without<Camera>, Without<Window>)>,
) {
    if keyboard_input.just_released(KeyCode::Q) {
        for entity in all_query.iter() {
            commands.entity(entity).despawn();
        }
    }
}
```

So now when I despawn everything and try to reload the Parallax I'm getting the error

https://github.com/ettoreleandrotognoli/bevy-parallax/blob/issue-27/examples/reload.rs
