### ISSUE TITLE
Wrong dependencies on crates.io-index for the 0.5.0 release

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [Corrosive-Games/bevy-parallax#29]
I don't know why, but when I install bevy-parallax 0.5.0 it is trying to use bevy 0.10 not bevy 0.11

I found it on the crates.io-index:
```json
{
	"name": "bevy-parallax",
	"vers": "0.5.0",
	"deps": [{
		"name": "bevy",
		"req": "^0.10.0",
		"features": ["bevy_render", "bevy_core_pipeline", "bevy_sprite", "bevy_asset", "bevy_winit"],
		"optional": false,
		"default_features": false,
		"target": null,
		"kind": "normal"
	}, {
		"name": "serde",
		"req": "^1.0.136",
		"features": [],
		"optional": false,
		"default_features": true,
		"target": null,
		"kind": "normal"
	}, {
		"name": "bevy",
		"req": "^0.10.0",
		"features": ["x11", "png"],
		"optional": false,
		"default_features": false,
		"target": null,
		"kind": "dev"
	}, {
		"name": "ron",
		"req": "^0.8.0",
		"features": [],
		"optional": false,
		"default_features": true,
		"target": null,
		"kind": "dev"
	}],
	"cksum": "12025beb406b3c0d61f982600c844316e297f8ec359e9a8fda23fa1daedb4a20",
	"features": {},
	"yanked": false
}
```
https://github.com/rust-lang/crates.io-index/blob/d69d90e8cfe3a3755754b027941faa4796c45666/be/vy/bevy-parallax#L7

There is something wrong with the release? Or maybe I'm having cache issues?

**Comment by ettoreleandrotognoli** [comment]
Oh, I see, there is no release after the bevy update commit

https://github.com/Corrosive-Games/bevy-parallax/commit/c3a36cc7a1eafd8263c3c70a15c776e71580ea9a

Thank you ^^

**Comment by ettoreleandrotognoli** [comment]
Looks like v0.4.0 and v0.5.0 are using the same version 0.5.0
Probably the  v0.5.0 release has the sources of the v0.4.0 tag

https://github.com/Corrosive-Games/bevy-parallax/blob/v0.5.0/Cargo.toml#L3
https://github.com/Corrosive-Games/bevy-parallax/blob/v0.4.0/Cargo.toml#L3

I created a PR https://github.com/Corrosive-Games/bevy-parallax/pull/30 to try to help

**Comment by odecay** [comment]
Ah this may have been my fault. I noticed after pushing a tag for v0.4 and v0.5 in close succession that the version in cargo.toml at the time of the v0.4 tag already had been bumped to 0.5.

**Comment by ettoreleandrotognoli** [comment]
My main concern it about what is in crates.io
If the published crate don't reflect the sources of the correspondent tag, maybe should be nice to yank them

**Comment by ettoreleandrotognoli** [comment]
Version [0.6.0](https://crates.io/crates/bevy-parallax/0.6.0/dependencies) is using bevy 0.11
