### ISSUE TITLE
Usage in README is out-of-date - "no `ParallaxResource` in root"

### ISSUE THREAD

**Issue by chaimpeck** [Corrosive-Games/bevy-parallax#40]
"no `ParallaxResource` in root".

The `examples` directory seems to have working examples, but just a heads up for anyone stuck on this.

**Comment by ekalosak** [comment]
Maintainers - this could be marked "good beginner issue", no?

**Comment by ettoreleandrotognoli** [comment]
I think I already fixed that and added a test to help us to keep it updated in this PR
https://github.com/Corrosive-Games/bevy-parallax/pull/32
